### ISSUE TITLE
Mcinfected addons

### ISSUE THREAD

**Issue by Plajer** [Bimmr/McInfected#115]
Hey! I wanna buy McInfected Leaderboard soon (https://www.spigotmc.org/resources/mcinfected-leaderboard.8309/) but i've got a question. For now it's inactive resource and i need to know that this resource will get future updates/fixes. Will it be updated if there will be any errors?
Another question is about Shop addon. Where it is? I can't find it on spigotmc. Is this addon deleted?

**Comment by Bimmr** [comment]
All the addons will get updates of they are needed.  And shops no longer
exists;   Everyone asked for it but as soon as I asked for at least 5
people who wanted to stress test it no one answered.

On Jan 7, 2017 6:46 AM, "Plajer" <notifications@github.com> wrote:

Hey! I wanna buy McInfected Leaderboard soon (https://www.spigotmc.org/
resources/mcinfected-leaderboard.8309/) but i've got a question. For now
it's inactive resource and i need to know that this resource will get
future updates/fixes. Will it be updated if there will be any errors?
Another question is about Shop addon. Where it is? I can't find it on
spigotmc. Is this addon deleted?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Bimmr/McInfected/issues/115>, or mute the thread
